#!/usr/bin/env Rscript
#options("gwasurvivr.cores"=8)

library(data.table)
require(optparse) #install.packages("optparse")
library(survminer)
library(survival)

print(sessionInfo())

option_list <- list(
  make_option("--phenofile", type="character", default="",
    help="path to the phenotype file generated by Pete with only independent samples"),
  make_option("--pheno", type="character", default="",
    help="path to the phenotype file generated by Pete with only independent samples"),
  make_option("--isbygenotype", type="logical", default=FALSE,
    help="by genotype"),
  make_option("--isflipAllele", type="logical", default=FALSE,
    help="flip genotype"),
  make_option("--marker", type="character", default="",
    help="marker"),
  make_option("--eventTimeBinSize", type="numeric", default=NULL,
    help="event time bin size")
)

## list of options
parser <- OptionParser(usage="%prog [options]", option_list=option_list)
args <- parse_args(parser, positional_arguments = 0)
opt <- args$options
print(opt)

data0 = fread(opt$phenofile, header=T, data.table=F)

if(opt$isbygenotype){
#phenofile = paste0("~/survival/realData/FinnGen/output_PoissonGLMM/download/merged/",opt$pheno,"_survival_p_lt_5e8.txt.markerlist.all.raw.pheno.txt")
#markerfile = paste0("/home/wei/survival/realData/FinnGen/output_PoissonGLMM/download/merged/",opt$pheno,"_survival_p_lt_5e8.txt.markerlist") 
#markerList = data.frame(fread(markerfile, header=F))
#/mnt/disk2/FinnGen/output_PoissonGLMM/R5/merged_0.36.6.1/plot/jobs

#outfile = paste0("/mnt/disk2/FinnGen/output_PoissonGLMM/R5/merged_0.36.6.1/plot/output/",opt$pheno, ".", opt$pheno, "_eventTimeBinsize_",opt$eventTimeBinSize, "_", opt$marker)
outfile = paste0(opt$pheno, ".", opt$pheno, "_eventTimeBinsize_",opt$eventTimeBinSize, "_", opt$marker)


  print("ok")

  datatest = data0[,c(opt$marker, "eventAge", "event")]
  datatest = datatest[complete.cases(datatest), ]
  if(!is.null(opt$eventTimeBinSize)){
    eventTimeBinSize = opt$eventTimeBinSize 
    minEventTime = min(datatest$eventAge[which(datatest$event == 1)])
    datatest$eventTimeNew = (datatest$eventAge - minEventTime) %/% eventTimeBinSize + 1
    datatest$eventAge = datatest$eventTimeNew 
  }


  colnames(datatest)[which(colnames(datatest) == opt$marker)] = "marker"
  print(sum(datatest$marker))

  if(opt$isflipAllele){datatest$marker = 2-datatest$marker}

  if(sum(datatest$marker == 2) <= 1 | sum(datatest$marker == 0) <= 1){
  	pdf(paste0(outfile,"_noconinf.pdf"))

  	km.fit <- survfit(Surv(eventAge, event) ~ marker, data = datatest)
  	km.surv <- ggsurvplot(km.fit, risk.table = TRUE, title = opt$marker)

  	print(km.surv)

  	dev.off()
  }else{
    	pdf(paste0(outfile, ".pdf"))

  	km.fit <- survfit(Surv(eventAge, event) ~ marker, data = datatest)
  	km.surv <- ggsurvplot(km.fit, risk.table = TRUE, conf.int=TRUE)

  	print(km.surv)
  	dev.off()

  }
}else{
#/mnt/disk2/FinnGen/output_PoissonGLMM/R5/merged_0.36.4
	#phenofolder="/home/wei/survival/realData/FinnGen/pheno/output_r5/withBirthYear/withBirthYear/"
	#phenofile=paste0(phenofolder, "r5_", opt$pheno,".pheno.txt")
	#phenofile=paste0("r6_", opt$pheno,".pheno.txt")

	#data0 = data.frame(fread(phenofile, header=T))
	data0 = data0[which(data0$eventAge < 105),]

	if(!is.null(opt$eventTimeBinSize)){
    		eventTimeBinSize = opt$eventTimeBinSize
    		minEventTime = min(data0$eventAge[which(data0$event == 1)])
    		data0$eventTimeNew = (data0$eventAge - minEventTime) %/% eventTimeBinSize + 1
    		data0$eventAge = data0$eventTimeNew
  	}


	#outfile = paste0("/mnt/disk2/FinnGen/output_PoissonGLMM/R5/merged_0.39/plot/output/",opt$pheno, "_overall")	
	#outfile = paste0("/mnt/disk2/FinnGen/output_PoissonGLMM/R5/merged_0.39/plot/output/",opt$pheno, "_eventTimeBinsize_",opt$eventTimeBinSize,"_overall")	
	outfile = paste0(opt$pheno, "_eventTimeBinsize_",opt$eventTimeBinSize,"_overall")	
	pdf(paste0(outfile, ".pdf"), height=11)

        km.fit <- survfit(Surv(eventAge, event) ~ 1, data = data0)
        km.surv <- ggsurvplot(km.fit, risk.table = TRUE, conf.int=TRUE, cumevents = TRUE,cumcensor=TRUE)

        print(km.surv)
        dev.off()

}
